apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-models-pvc
  labels:
    app: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-static-pvc
  labels:
    app: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
