apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
type: Opaque
data:
  # Base64 encoded placeholder values (admin:adminpassword)
  MONGODB_USER: YWRtaW4=
  MONGODB_PASS: YWRtaW5wYXNzd29yZA==
